### PR TITLE
#877 python service bus template

### PR DESCRIPTION
**Pull request by t-eckert**
This PR addresses Issue #877.

- Uses Black formatting
- Logging content type and body
- Added README file, but no docs yet. 

More work will need to be done, but I wanted to start getting feedback so I go in the right direction.

### CODE REVIEW

**Comment by Stanpol** [comment]
Without this PR a default service bus template is not working, due to few lines missing in function.json. Looking forward for a merge!

**Comment by t-eckert** [comment]
Is this ready to be merged?

**Comment by maiqbal11** [comment]
@t-eckert, yes, we should be good on this. Feel free to merge.

**Comment by t-eckert** [comment]
I don't have write permission :/

**Pull request merged**
