### PR TITLE
Update SQL C# templates with latest version of package (0.1.457-preview)

### PR DESCRIPTION
**Pull request by Charles-Gagnon**

### CODE REVIEW

**Review by soninaren — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@soninaren I can't merge this in, can you do that for us? (or @lucyzhang929, I seem to recall you being able to do that yourself in the past?)

**Comment by lucyzhang929** [comment]
Yes I can merge. I see an install package error in the pipeline though - rerunning to see if it is a transient network issue.

**Comment by Charles-Gagnon** [comment]
@soninaren This error doesn't seem related to our PR - is this a known issue?

```
OneLocBuildClient.exe Information: 0 : CredentialProvider.VSS: Exit message: Auth tokens could not be retrieved. Remove the -NonInteractive flag and try again
OneLocBuildClient.exe Information: 0 : CredentialProvider.VSS: Exit code: Failure
OneLocBuildClient.exe Information: 0 : Unable to load the service index for source https://ceapex.pkgs.visualstudio.com/_packaging/LocTools/nuget/v3/index.json.
OneLocBuildClient.exe Information: 0 :   Response status code does not indicate success: 401 (Unauthorized).
```

**Comment by Charles-Gagnon** [comment]
@soninaren This is still failing...any update?

**Pull request merged**
