### PR TITLE
Adding IoT Hub trigger

### PR DESCRIPTION
**Pull request by jimbobbennett**
Re-raising #1059 with updates based off the new bundle nuspecs.

Fixies #1052

### CODE REVIEW

**Comment by jimbobbennett** [comment]
Tagging @vrdmr, same as the previous PR. 

Tagging @soninaren as PRs only seem to build when they raise them. @soninaren - if there's no way to fix builds so anyone other than you can raise PRs, can you re-raise this yourself?

**Comment by soninaren** [comment]
The build should be fixed now

**Comment by soninaren** [comment]
> The build should be fixed now

Looks like a spoke too soon, there may be a permissions issue here.

**Comment by soninaren** [comment]
@jimbobbennett barring the build issue, were you able to test the new templates for all the bundle versions in the PR?

**Comment by jimbobbennett** [comment]
These were tested by building locally and testing with Azure Functions Core tools.

**Review by soninaren — COMMENTED** [review]
cc: @alrod Can you take a look at this PR?

**Comment by mattchenderson** [comment]
Is this still relevant?

@alrod

**Pull request closed without merging**
