### PR TITLE
Renamed VS display names for properties

### PR DESCRIPTION
**Pull request by jeffhollan**
Not sure where the v2 templates are to make similar changes

### CODE REVIEW

**Comment by jeffhollan** [comment]
Related to issue #599

**Comment by paulbatum** [comment]
I'm not sure if this change actually achieves what you're looking for. There's a workflow you can use to test template changes, but I'm not sure where its documented (doesn't look like its in the repro wiki). Might need to sit on this change until @soninaren gets back.

**Comment by soninaren** [comment]
@jeffhollan  the properties you are looking for vs-2017.3.host.json. The text property corresponds to the display text in visual studio. We would also need make the same changes in v2.x branch.
https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Functions.Templates/Templates/BlobTrigger-CSharp/build.config/vs-2017.3.host.json#L23

All the documentation related to VS template should be in templating wiki for dotnet. I will some additional documentation in the repo wiki to make it easily accessible.

**Comment by EhRom** [comment]
@DamiaoCastro, could this pull request can contain the fix for this issue https://github.com/Azure/Azure-Functions/issues/652#issuecomment-360980571 ?

**Comment by DamiaoCastro** [comment]
@EhRom , this seems to be changes on the VS templates only. Not the functionality that generates the "function.json" file, if I'm not mistaken. Maybe that's part of another PR.

**Comment by soninaren** [comment]
This changes in the PR has been already

**Comment by soninaren** [comment]
@DamiaoCastro VS update should this https://github.com/Azure/Azure-Functions/issues/652 issue.

**Pull request closed without merging**
