### PR TITLE
Update Cosmos DB templates

### PR DESCRIPTION
**Pull request by jcocchi**
Updating Cosmos DB templates for extension version 4.x and extension bundles v4

### CODE REVIEW

**Comment by lilyjma** [comment]
@soninaren - As discussed today, retirement of the old cosmos extension will be public 8/21. Please review this PR and make sure that by that date, customers can see and use templates based on the new version of the extension. Thanks!

**Comment by lilyjma** [comment]
@soninaren - could you prioritize reviewing this PR? I believe we're stuck with VSCode defaulting to bundles v3 because we're missing this template for v4. @nturinski - please correct me if I'm wrong. Thanks!

**Comment by nturinski** [comment]
Could you please verify that this got shipped? We're still not seeing the CosmosDB trigger for Typescript on version [4.9.0](https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.9.0/StaticContent/v1/templates/templates.json)

**Comment by lilyjma** [comment]
Thanks Nathan - I pinged @soninaren offline about this.

**Pull request merged**
