### PR TITLE
Add cosmosdb powershell template

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
This adds a CosmosDB template for PowerShell function apps.

cc @daxian-dbw @SteveL-MSFT @pragnagopa @christopheranderson :)

### CODE REVIEW

**Comment by pragnagopa** [comment]
@soninaren - how can we test this locally?

**Comment by soninaren** [comment]
> @soninaren - how can we test this locally?

You would have to create a cosmos db resource and then add a document with in the database.

**Comment by TylerLeonhardt** [comment]
@soninaren I know that the function itself works - I want to make sure that this PR properly adds the template to the available templates for PowerShell in core tools.

I see appveyor has the template in this PR inside of the nuget package is that enough verification?

**Comment by soninaren** [comment]
@TylerLeonhardt Currently we update the template in core tools manually. From a verification stand point the only thing you would be able to verify is that the templates are present in the artifacts from app veyor build.

**Pull request merged**
